print('partition -> divide uma string em uma tupla de 3 elementos. Ex.:')
print('aroldofernandosouza'.partition('fernando'))
print('aroldofernandosouza'.partition('aroldo'))
print()
print('xyzxyx'.partition('z'))
print('xyzxyx'.partition('x'))
print()

print('rpartition -> divide uma string em uma tupla de 3 elementos de trás para frente Ex.:')
print('aroldofernandosouza'.rpartition('fernando'))
print('aroldofernandosouza'.rpartition('aroldo'))
print()
print('xyzxyx'.rpartition('z'))
print('xyzxyx'.rpartition('x'))
print()

print('split -> Divide a String em um Lista')
print('Conan Bruce Tininha Suzi Branca Pituquinha')
print('Conan Bruce Tininha Suzi Branca Pituquinha'.split())
print()
print('Por padrão é o espaço como separador, mas vc pode esquecificar, por ex.:')
print('Conan;Bruce;Tininha;Suzi;Branca;Pituquinha')
print('Conan;Bruce;Tininha;Suzi;Branca;Pituquinha'.split(';'))
print()

print('rsplit -> Divide a String em um Lista de tras pra frente')
print('Conan Bruce Tininha Suzi Branca Pituquinha')
print('Conan Bruce Tininha Suzi Branca Pituquinha'.rsplit())
print()
print('Por padrão é o espaço como separador, mas vc pode esquecificar, por ex.:')
print('Conan;Bruce;Tininha;Suzi;Branca;Pituquinha')
print('Conan;Bruce;Tininha;Suzi;Branca;Pituquinha'.rsplit(';'))
